const fs = require('fs');

let css = fs.readFileSync('src/index.css', 'utf8');

// We want to replace `.bg-\[\#130f26\]` with `.bg-\[\#130f26\]:not(.always-dark):not(.always-dark *)`
// But we only want to do this for the generated overrides which are at the end of the file.

const parts = css.split('/* AUTOGENERATED COMPREHENSIVE LIGHT MODE OVERRIDES - FULL */');
if (parts.length === 2) {
  let overrides = parts[1];
  
  // Regex to match the class selectors in the overrides part
  overrides = overrides.replace(/\.((?:hover\\:|active\\:|focus\\:)?[a-z-]+\-\\\\[#a-zA-Z0-9\\\\]+)(?::(?:hover|active|focus))?/g, (match) => {
    return match + ':not(.always-dark):not(.always-dark *)';
  });
  
  // also handle .text-white
  overrides = overrides.replace(/\.text-white/g, '.text-white:not(.always-dark):not(.always-dark *)');
  overrides = overrides.replace(/\.hover\\:text-white:hover/g, '.hover\\:text-white:hover:not(.always-dark):not(.always-dark *)');
  
  fs.writeFileSync('src/index.css', parts[0] + '/* AUTOGENERATED COMPREHENSIVE LIGHT MODE OVERRIDES - FULL */' + overrides);
  console.log("Updated index.css with .always-dark exclusions.");
} else {
  console.log("Could not find the autogenerated marker.");
}

