const fs = require('fs');
const path = require('path');

const walkSync = (dir, filelist = []) => {
  fs.readdirSync(dir).forEach(file => {
    const dirFile = path.join(dir, file);
    if (fs.statSync(dirFile).isDirectory()) {
      filelist = walkSync(dirFile, filelist);
    } else if (dirFile.endsWith('.tsx') || dirFile.endsWith('.ts')) {
      filelist.push(dirFile);
    }
  });
  return filelist;
};

const files = walkSync('./src/components');
const classes = new Set();

const regex = /(?:hover:|active:|focus:)?(?:bg|text|border)-\[#([0-9a-fA-F]{6})\](?:\/([0-9]+))?/g;

files.forEach(file => {
  const content = fs.readFileSync(file, 'utf8');
  let match;
  while ((match = regex.exec(content)) !== null) {
    classes.add(match[0]);
  }
});

const getLuminance = (hex) => {
  const r = parseInt(hex.substring(0, 2), 16) / 255;
  const g = parseInt(hex.substring(2, 4), 16) / 255;
  const b = parseInt(hex.substring(4, 6), 16) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

const isGrayScaleOrDark = (hex) => {
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  if (getLuminance(hex) < 0.15) return true;
  if (['20183e', '281e4b', '201642', '1f1742', '202c33', '111b21', '374248', 'a29bfe', '8696a0', 'e9edef', 'f1f2f6', 'ffffff'].includes(hex)) return true;
  return (max - min) < 40; 
};

console.log("  /* AUTOGENERATED COMPREHENSIVE LIGHT MODE OVERRIDES - FULL */");
const rules = [];

classes.forEach(cls => {
  const typeMatch = cls.match(/^(?:hover:|active:|focus:)?(bg|text|border)-/);
  const hexMatch = cls.match(/\[#([0-9a-fA-F]{6})\]/);
  const opacityMatch = cls.match(/\/([0-9]+)$/);
  const pseudoMatch = cls.match(/^(hover|active|focus):/);
  
  if (!typeMatch || !hexMatch) return;
  
  const type = typeMatch[1];
  const hex = hexMatch[1].toLowerCase();
  const opacity = opacityMatch ? parseInt(opacityMatch[1]) : 100;
  const pseudo = pseudoMatch ? pseudoMatch[1] : '';
  
  if (hex === '00b894' || hex === 'fd79a8' || hex === '005c4b' || hex === '55efc4' || !isGrayScaleOrDark(hex)) return;
  
  let targetColor = '';
  
  if (type === 'bg') {
    const lum = getLuminance(hex);
    if (lum < 0.05) targetColor = '241 245 249'; // #f1f5f9
    else if (lum < 0.1) targetColor = '255 255 255'; // #ffffff
    else targetColor = '248 250 252'; // #f8fafc
    if (pseudo === 'hover') targetColor = '226 232 240'; // #e2e8f0
  } else if (type === 'border') {
    targetColor = '226 232 240'; // #e2e8f0
  } else if (type === 'text') {
    if (['a29bfe', '8696a0', '54656f'].includes(hex)) targetColor = '100 116 139'; // #64748b
    else targetColor = '15 23 42'; // #0f172a
  }
  
  if (!targetColor) return;
  
  // Create selector, escaping [ ] and # and /
  const escapedCls = cls.replace(/\[/g, '\\[').replace(/\]/g, '\\]').replace(/#/g, '\\#').replace(/\//g, '\\/');
  
  const selectors = `:root.light .${escapedCls}${pseudo ? `:${pseudo}` : ''}, :root[data-theme-mode="light"] .${escapedCls}${pseudo ? `:${pseudo}` : ''}`;
  
  const prop = type === 'bg' ? 'background-color' : type === 'border' ? 'border-color' : 'color';
  const val = opacity < 100 ? `rgb(${targetColor} / ${opacity}%)` : `rgb(${targetColor})`;
  
  rules.push(`${selectors} { ${prop}: ${val} !important; }`);
});

rules.sort();
rules.forEach(r => console.log(r));

